<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions
     name="dbAuditoria"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ClaseTresTarde/Pulling/dbAuditoria"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ClaseTresTarde/Pulling/dbAuditoria"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbAuditoria"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbAuditoria_plt" >
    <plt:role name="dbAuditoria_role" >
      <plt:portType name="tns:dbAuditoria_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbAuditoria" schemaLocation="dbAuditoria_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PersonaCollection_msg">
        <wsdl:part name="PersonaCollection" element="top:PersonaCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbAuditoria_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:PersonaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="dbAuditoria_table.xsd" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbAuditoria" ref="Pulling/Resources/dbAuditoria_table"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/ClaseTresTarde/Pulling/dbAuditoria</con:targetNamespace>
</con:wsdlEntry>